using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class tocarCancion : MonoBehaviour
{
    public GameObject Do;
    public GameObject Re;
    public GameObject Mi;
    public GameObject Fa;
    public GameObject Sol;
    public GameObject La;
    public GameObject Si;
    public GameObject Do1;
    public GameObject Re1;
    public GameObject Mi1;
    public GameObject Do_s;
    public GameObject Re_s;
    public GameObject Fa_s;
    public GameObject Sol_s;
    public GameObject Bb;
    public GameObject Do1_s;
    public GameObject Re1_s;

    // Propiedades
    public tecla teclaDo;
    public tecla teclaFa_s;
    public tecla teclaBb;
    public tecla teclaRe1_s;
    public tecla teclaDo1_s;
    public tecla teclaFa;
    public tecla teclaRe_s;
    public tecla teclaSol_s;
    public tecla teclaDo_s;
    public tecla teclaSi;
    public tecla teclaDo1;
    public bool flag=true;
    // Start is called before the first frame update
    void Start()
    {
        teclaDo = Do.GetComponent<tecla>();
        teclaFa_s = Fa_s.GetComponent<tecla>();
        teclaBb = Bb.GetComponent<tecla>();
        teclaRe1_s = Re1_s.GetComponent<tecla>();
        teclaDo1_s = Do1_s.GetComponent<tecla>();
        teclaFa = Fa.GetComponent<tecla>();
        teclaRe_s = Re_s.GetComponent<tecla>();
        teclaSol_s = Sol_s.GetComponent<tecla>();
        teclaDo_s = Do_s.GetComponent<tecla>();
        teclaSi = Si.GetComponent<tecla>();
        teclaDo1 = Do1.GetComponent<tecla>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    private void OnMouseDown()
    {
        if (flag)
        {
            tocarMelodia();
            flag = true;
        }
        
    }
    void tocarMelodia()
    {
        flag = false;
        StartCoroutine(TocarTecla());
    }
    IEnumerator TocarTecla()
    {
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(1f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(1f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.7f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaDo_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaBb.tocar();
        yield return new WaitForSeconds(1f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.4f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(1f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.7f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.6f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(1f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.7f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.6f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.6f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.6f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.6f);
        teclaRe1_s.tocar();
        yield return new WaitForSeconds(0.7f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaBb.tocar();
        yield return new WaitForSeconds(1f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.25f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.25f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.25f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa.tocar();
        yield return new WaitForSeconds(1f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo_s.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.65f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.45f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaFa_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaSi.tocar();
        yield return new WaitForSeconds(1f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaDo1_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.5f);
        teclaSol_s.tocar();
        yield return new WaitForSeconds(0.35f);
        teclaSi.tocar();
        yield return new WaitForSeconds(1f);
        teclaRe_s.tocar();
        yield return new WaitForSeconds(0.5f);
        teclaSi.tocar();
        yield return new WaitForSeconds(0.8f);
        teclaBb.tocar();
        yield return new WaitForSeconds(0.5f);
    }
} 
